spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
  datasource:
    url: jdbc:postgresql://192.168.0.12:5432/jmalcloud?currentSchema=public
    driver-class-name: org.postgresql.Driver
    username: jmalcloud
    password: xxx
jmalcloud:
  datasource:
    type: pgsql
    migration: false
