spring:
  data:
    mongodb:
      uri: mongodb://${DATABASE_HOST:localhost}:${DATABASE_PORT:27017}/jmalcloud
      database: ${DATABASE_NAME:jmalcloud}
  flyway:
    enabled: false
jmalcloud:
  datasource:
    type: mongodb
    mongo-enabled: true
logging:
  level:
    org:
      springframework:
        data:
          repository:
            config:
              RepositoryConfigurationDelegate: off
