spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
  datasource:
    url: jdbc:postgresql://${PGSQL_HOST:localhost}:${PGSQL_PORT:5432}/${PGSQL_DATABASE:jmalcloud}
    driver-class-name: org.postgresql.Driver
    username: ${PGSQL_USER:jmalcloud}
    password: ${PGSQL_PASSWORD:jmalcloud}
  flyway:
    locations:
      - classpath:db/migration/postgresql
jmalcloud:
  datasource:
    type: pgsql
    migration: false
    jpa-enabled: true
    mongo-enabled: false
