spring:
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
  datasource:
    url: jdbc:sqlite:${file.rootDir}/${file.dbDir}/db/jmalcloud.db
    driver-class-name: org.sqlite.JDBC
    name: jmalcloud
    username:
    password:
jmalcloud:
  datasource:
    type: sqlite
    migration: false
