spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
  datasource:
    url: jdbc:mysql://localhost:3306/jmalcloud?useUnicode=true&characterEncoding=UTF8&useSSL=false&useUnicode=true&serverTimezone=GMT&connectTimeout=60000&socketTimeout=60000
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: xxx
jmalcloud:
  datasource:
    type: mysql
    migration: false
