spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.ldap.LdapAutoConfiguration
      - org.springframework.boot.autoconfigure.data.ldap.LdapRepositoriesAutoConfiguration
logging:
  level:
    root: info
jmalcloud:
  datasource:
    migration: true
    mongo-enabled: true
    jpa-enabled: true
