FROM ubuntu:22.04 AS builder

ENV DEBIAN_FRONTEND=noninteractive

WORKDIR /build
ARG TARGETARCH
ENV ARCH=${TARGETARCH}

RUN apt-get update && \
    apt-get install -y wget && \
    wget https://github.com/jamebal/jmal-cloud-server/releases/download/v2.14.0/mxcad_${ARCH}.zip && \
    \
    # 解压 mxcad
    unzip -o mxcad_${ARCH}.zip -d /output && \
    mv /output/mxcad_${ARCH} /output/mxcad && \
    chmod -R 777 /output/mxcad/mxcadassembly && \
    chmod -R 777 /output/mxcad/mx/so/* && \


FROM ghcr.io/jamebal/jmalcloud_base:latest

# --- 从构建器阶段复制处理好的应用文件 ---
COPY --from=builder /output/mxcad /usr/local/mxcad
COPY --from=builder /output/mxcad/mx/locale /usr/local/share/locale
