--
-- PostgreSQL database dump
--

-- Dumped from database version 17.6 (Debian 17.6-2.pgdg13+1)
-- Dumped by pg_dump version 17.5

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_table_access_method = heap;

--
-- Name: access_token; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.access_token (
    create_time timestamp(6) without time zone,
    last_active_time timestamp(6) without time zone,
    id character varying(24) NOT NULL,
    access_token character varying(255),
    name character varying(255),
    username character varying(255)
);


--
-- Name: articles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.articles (
    alone_page boolean,
    has_draft boolean,
    is_release boolean,
    page_sort integer,
    file_id bigint NOT NULL,
    id bigint NOT NULL,
    cover character varying(255),
    public_id character varying(255) NOT NULL,
    slug character varying(255),
    category_ids jsonb,
    tag_ids jsonb
);


--
-- Name: articles_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.articles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.articles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: category; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.category (
    is_default boolean,
    id character varying(24) NOT NULL,
    parent_category_id character varying(24),
    slug character varying(24),
    user_id character varying(24),
    name character varying(32),
    category_background character varying(255),
    description character varying(255)
);


--
-- Name: consumers; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.consumers (
    creator boolean,
    mfa_enabled boolean,
    quota integer,
    webp_disabled boolean,
    created_time timestamp(6) without time zone,
    take_up_space bigint,
    updated_time timestamp(6) without time zone,
    id character varying(24) NOT NULL,
    avatar character varying(255),
    introduction character varying(255),
    mfa_secret text,
    password character varying(255),
    show_name character varying(255),
    slogan text,
    username character varying(255),
    roles jsonb
);


--
-- Name: direct_links; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.direct_links (
    downloads bigint,
    update_date timestamp(6) without time zone,
    mark character varying(16),
    file_id character varying(24),
    id character varying(24) NOT NULL,
    user_id character varying(24)
);


--
-- Name: file_history; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.file_history (
    size bigint,
    upload_date timestamp(6) without time zone,
    id character varying(24) NOT NULL,
    charset character varying(255),
    compression character varying(255),
    file_id character varying(255),
    filename character varying(255),
    filepath character varying(255),
    operator character varying(255),
    "time" character varying(255)
);


--
-- Name: file_props; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.file_props (
    share_base boolean,
    sub_share boolean,
    transcode_video integer,
    id bigint NOT NULL,
    share_id character varying(24),
    public_id character varying(255) NOT NULL,
    remark character varying(255),
    props jsonb,
    share_props jsonb,
    tags jsonb
);


--
-- Name: file_props_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.file_props ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.file_props_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: files; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.files (
    del_tag integer,
    etag_update_failed_attempts integer,
    has_content boolean NOT NULL,
    has_content_text boolean NOT NULL,
    has_html boolean NOT NULL,
    is_favorite boolean,
    is_folder boolean,
    lucene_index integer,
    needs_etag_update boolean,
    id bigint NOT NULL,
    last_etag_update_request_at timestamp(6) without time zone,
    props_id bigint NOT NULL,
    size bigint,
    update_date timestamp(6) without time zone NOT NULL,
    upload_date timestamp(6) without time zone NOT NULL,
    user_id character varying(24) NOT NULL,
    suffix character varying(32),
    etag character varying(64),
    content_type character varying(128),
    last_etag_update_error text,
    md5 character varying(255),
    mount_file_id character varying(255),
    name character varying(255) NOT NULL,
    oss_folder character varying(255),
    path character varying(255) NOT NULL,
    public_id character varying(255) NOT NULL
);


--
-- Name: files_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.files ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.files_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: heartwings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.heartwings (
    create_time timestamp(6) without time zone,
    id character varying(24) NOT NULL,
    creator character varying(255),
    heartwings character varying(255),
    username character varying(255)
);


--
-- Name: ldap_config; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.ldap_config (
    enable boolean,
    id character varying(24) NOT NULL,
    basedn character varying(255),
    ldap_server character varying(255),
    login_name character varying(255),
    password character varying(255),
    user_id character varying(255),
    userdn character varying(255),
    roles jsonb
);


--
-- Name: log; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.log (
    status integer,
    create_time timestamp(6) without time zone,
    id bigint NOT NULL,
    "time" bigint,
    method character varying(10),
    type character varying(16),
    file_user_id character varying(24),
    operation_module character varying(24),
    ip character varying(40),
    browser character varying(64),
    device_model character varying(64),
    operating_system character varying(64),
    operation_fun character varying(96),
    filepath character varying(255),
    public_id character varying(255) NOT NULL,
    remarks character varying(255),
    show_name character varying(255),
    url character varying(255),
    username character varying(255),
    ip_info jsonb
);


--
-- Name: log_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: menu; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.menu (
    hide boolean,
    menu_type integer,
    sort_number integer,
    create_time timestamp(6) without time zone,
    update_time timestamp(6) without time zone,
    id character varying(24) NOT NULL,
    parent_id character varying(24),
    name character varying(32),
    authority character varying(64),
    component character varying(255),
    icon character varying(255),
    path character varying(255)
);


--
-- Name: ocr_config; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.ocr_config (
    enable boolean,
    max_tasks integer,
    created_time timestamp(6) without time zone,
    updated_time timestamp(6) without time zone,
    id character varying(24) NOT NULL,
    ocr_engine character varying(255),
    CONSTRAINT ocr_config_max_tasks_check CHECK (((max_tasks <= 8) AND (max_tasks >= 1)))
);


--
-- Name: office_config; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.office_config (
    token_enabled boolean,
    created_time timestamp(6) without time zone,
    updated_time timestamp(6) without time zone,
    id character varying(24) NOT NULL,
    callback_server character varying(255),
    document_server character varying(255),
    secret character varying(255),
    format jsonb
);


--
-- Name: oss_config; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.oss_config (
    platform smallint,
    created_time timestamp(6) without time zone,
    updated_time timestamp(6) without time zone,
    id character varying(24) NOT NULL,
    user_id character varying(24),
    access_key character varying(255),
    bucket character varying(255),
    endpoint character varying(255),
    folder_name character varying(255),
    region character varying(255),
    secret_key character varying(255),
    CONSTRAINT oss_config_platform_check CHECK (((platform >= 0) AND (platform <= 2)))
);


--
-- Name: role; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.role (
    create_time timestamp(6) without time zone,
    update_time timestamp(6) without time zone,
    id character varying(24) NOT NULL,
    code character varying(32),
    name character varying(32),
    remarks character varying(255),
    menus jsonb
);


--
-- Name: search_history; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.search_history (
    exact_search boolean,
    include_file_content boolean,
    include_file_name boolean,
    include_tag_name boolean,
    is_favorite boolean,
    is_folder boolean,
    search_mount boolean,
    search_overall boolean,
    modify_end bigint,
    modify_start bigint,
    search_time bigint,
    size_max bigint,
    size_min bigint,
    id character varying(24) NOT NULL,
    current_directory character varying(255),
    folder character varying(255),
    keyword character varying(255),
    tag_id character varying(255),
    type character varying(255),
    user_id character varying(255)
);


--
-- Name: share; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.share (
    is_folder boolean,
    is_privacy boolean,
    create_date timestamp(6) without time zone,
    expire_date timestamp(6) without time zone,
    extraction_code character varying(8),
    father_share_id character varying(24),
    id character varying(24) NOT NULL,
    short_id character varying(24),
    user_id character varying(24),
    content_type character varying(128),
    file_id character varying(255),
    file_name character varying(255),
    operation_permission_list jsonb
);


--
-- Name: tag; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tag (
    sort integer,
    color character varying(16),
    id character varying(24) NOT NULL,
    name character varying(32),
    slug character varying(32),
    tag_background character varying(255),
    user_id character varying(255)
);


--
-- Name: transcode_config; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.transcode_config (
    bitrate integer,
    bitrate_cond integer,
    enable boolean,
    frame_rate double precision,
    frame_rate_cond integer,
    height integer,
    height_cond integer,
    is_re_transcode boolean,
    max_threads integer,
    vtt_thumbnail_count integer,
    created_time timestamp(6) without time zone,
    updated_time timestamp(6) without time zone,
    id character varying(24) NOT NULL,
    CONSTRAINT transcode_config_bitrate_check CHECK (((bitrate >= 100) AND (bitrate <= 1000000))),
    CONSTRAINT transcode_config_bitrate_cond_check CHECK (((bitrate_cond <= 1000000) AND (bitrate_cond >= 100))),
    CONSTRAINT transcode_config_frame_rate_check CHECK (((frame_rate <= (120)::double precision) AND (frame_rate >= (1)::double precision))),
    CONSTRAINT transcode_config_frame_rate_cond_check CHECK (((frame_rate_cond <= 120) AND (frame_rate_cond >= 1))),
    CONSTRAINT transcode_config_height_check CHECK (((height >= 100) AND (height <= 10000))),
    CONSTRAINT transcode_config_height_cond_check CHECK (((height_cond >= 100) AND (height_cond <= 10000))),
    CONSTRAINT transcode_config_max_threads_check CHECK (((max_threads <= 8) AND (max_threads >= 1))),
    CONSTRAINT transcode_config_vtt_thumbnail_count_check CHECK (((vtt_thumbnail_count >= 1) AND (vtt_thumbnail_count <= 256)))
);


--
-- Name: trash; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.trash (
    has_content boolean,
    hidden boolean,
    is_folder boolean,
    move boolean,
    id bigint NOT NULL,
    size bigint,
    update_date timestamp(6) without time zone,
    upload_date timestamp(6) without time zone,
    user_id character varying(24),
    suffix character varying(32),
    content_type character varying(128),
    md5 character varying(255),
    name character varying(255),
    path character varying(255),
    public_id character varying(255) NOT NULL,
    props jsonb
);


--
-- Name: trash_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.trash ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.trash_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: website_setting; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.website_setting (
    mfa_force_enable boolean,
    id character varying(24) NOT NULL,
    archive_background character varying(255),
    background_desc_site character varying(255),
    background_site character varying(255),
    background_text_site character varying(255),
    category_background character varying(255),
    copyright character varying(255),
    footer_html text,
    iframe text,
    netdisk_logo character varying(255),
    netdisk_name character varying(255),
    network_record_number character varying(255),
    network_record_number_str character varying(255),
    operating_buttons text,
    record_permission_num character varying(255),
    site_ico character varying(255),
    site_logo character varying(255),
    site_name character varying(255),
    site_url character varying(255),
    tag_background character varying(255),
    alone_pages jsonb
);


--
-- Name: access_token access_token_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.access_token
    ADD CONSTRAINT access_token_pkey PRIMARY KEY (id);


--
-- Name: articles articles_file_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.articles
    ADD CONSTRAINT articles_file_id_key UNIQUE (file_id);


--
-- Name: articles articles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.articles
    ADD CONSTRAINT articles_pkey PRIMARY KEY (id);


--
-- Name: articles articles_public_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.articles
    ADD CONSTRAINT articles_public_id_key UNIQUE (public_id);


--
-- Name: category category_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.category
    ADD CONSTRAINT category_pkey PRIMARY KEY (id);


--
-- Name: consumers consumers_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.consumers
    ADD CONSTRAINT consumers_pkey PRIMARY KEY (id);


--
-- Name: direct_links direct_links_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.direct_links
    ADD CONSTRAINT direct_links_pkey PRIMARY KEY (id);


--
-- Name: file_history file_history_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.file_history
    ADD CONSTRAINT file_history_pkey PRIMARY KEY (id);


--
-- Name: file_props file_props_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.file_props
    ADD CONSTRAINT file_props_pkey PRIMARY KEY (id);


--
-- Name: file_props file_props_public_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.file_props
    ADD CONSTRAINT file_props_public_id_key UNIQUE (public_id);


--
-- Name: files files_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.files
    ADD CONSTRAINT files_pkey PRIMARY KEY (id);


--
-- Name: files files_props_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.files
    ADD CONSTRAINT files_props_id_key UNIQUE (props_id);


--
-- Name: files files_public_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.files
    ADD CONSTRAINT files_public_id_key UNIQUE (public_id);


--
-- Name: heartwings heartwings_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.heartwings
    ADD CONSTRAINT heartwings_pkey PRIMARY KEY (id);


--
-- Name: ldap_config ldap_config_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ldap_config
    ADD CONSTRAINT ldap_config_pkey PRIMARY KEY (id);


--
-- Name: log log_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.log
    ADD CONSTRAINT log_pkey PRIMARY KEY (id);


--
-- Name: log log_public_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.log
    ADD CONSTRAINT log_public_id_key UNIQUE (public_id);


--
-- Name: menu menu_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.menu
    ADD CONSTRAINT menu_pkey PRIMARY KEY (id);


--
-- Name: ocr_config ocr_config_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ocr_config
    ADD CONSTRAINT ocr_config_pkey PRIMARY KEY (id);


--
-- Name: office_config office_config_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.office_config
    ADD CONSTRAINT office_config_pkey PRIMARY KEY (id);


--
-- Name: oss_config oss_config_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.oss_config
    ADD CONSTRAINT oss_config_pkey PRIMARY KEY (id);


--
-- Name: role role_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.role
    ADD CONSTRAINT role_pkey PRIMARY KEY (id);


--
-- Name: search_history search_history_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.search_history
    ADD CONSTRAINT search_history_pkey PRIMARY KEY (id);


--
-- Name: share share_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.share
    ADD CONSTRAINT share_pkey PRIMARY KEY (id);


--
-- Name: tag tag_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tag
    ADD CONSTRAINT tag_pkey PRIMARY KEY (id);


--
-- Name: transcode_config transcode_config_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.transcode_config
    ADD CONSTRAINT transcode_config_pkey PRIMARY KEY (id);


--
-- Name: trash trash_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.trash
    ADD CONSTRAINT trash_pkey PRIMARY KEY (id);


--
-- Name: trash trash_public_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.trash
    ADD CONSTRAINT trash_public_id_key UNIQUE (public_id);


--
-- Name: website_setting website_setting_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.website_setting
    ADD CONSTRAINT website_setting_pkey PRIMARY KEY (id);


--
-- Name: articles_slug; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX articles_slug ON public.articles USING btree (slug);


--
-- Name: direct_links_file_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX direct_links_file_id ON public.direct_links USING btree (file_id);


--
-- Name: direct_links_mark; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX direct_links_mark ON public.direct_links USING btree (mark);


--
-- Name: file_history_links_file_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX file_history_links_file_id ON public.file_history USING btree (file_id);


--
-- Name: files_del_tag; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX files_del_tag ON public.files USING btree (del_tag);


--
-- Name: files_is_folder; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX files_is_folder ON public.files USING btree (is_folder);


--
-- Name: files_mount_file_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX files_mount_file_id ON public.files USING btree (mount_file_id);


--
-- Name: files_name; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX files_name ON public.files USING btree (name);


--
-- Name: files_path; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX files_path ON public.files USING btree (path);


--
-- Name: files_size; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX files_size ON public.files USING btree (size);


--
-- Name: files_update_date; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX files_update_date ON public.files USING btree (update_date);


--
-- Name: files_upload_date; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX files_upload_date ON public.files USING btree (upload_date);


--
-- Name: files_user_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX files_user_id ON public.files USING btree (user_id);


--
-- Name: log_create_time; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX log_create_time ON public.log USING btree (create_time);


--
-- Name: log_ip; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX log_ip ON public.log USING btree (ip);


--
-- Name: log_type; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX log_type ON public.log USING btree (type);


--
-- Name: log_username; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX log_username ON public.log USING btree (username);


--
-- Name: search_history_keyword; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX search_history_keyword ON public.search_history USING btree (keyword);


--
-- Name: search_history_search_time; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX search_history_search_time ON public.search_history USING btree (search_time);


--
-- Name: search_history_user_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX search_history_user_id ON public.search_history USING btree (user_id);


--
-- Name: share_short_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX share_short_id ON public.share USING btree (short_id);


--
-- Name: trash_name; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX trash_name ON public.trash USING btree (name);


--
-- Name: trash_path; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX trash_path ON public.trash USING btree (path);


--
-- Name: trash_trash_user_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX trash_trash_user_id ON public.trash USING btree (user_id);


--
-- Name: trash_update_date; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX trash_update_date ON public.trash USING btree (update_date);


--
-- Name: trash_upload_date; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX trash_upload_date ON public.trash USING btree (upload_date);

