name: Copy jmalcloud_native:test to jmalcloud:test

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  copy-tags:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_IO_USERNAME }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Copy Docker Hub tag jmalcloud_native:test -> jmalcloud:test
        run: |
          docker buildx imagetools create \
            -t jmal/jmalcloud:test \
            jmal/jmalcloud_native:test

      - name: Copy GHCR tag jmalcloud_native:test -> jmalcloud:test
        run: |
          docker buildx imagetools create \
            -t ghcr.io/${{ secrets.GHCR_IO_USERNAME }}/jmalcloud:test \
            ghcr.io/${{ secrets.GHCR_IO_USERNAME }}/jmalcloud_native:test
